/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as ImoveisIndexRouteImport } from './routes/imoveis.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos.$slug'
import { Route as ImoveisSlugRouteImport } from './routes/imoveis.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const ImoveisIndexRoute = ImoveisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImoveisRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const ImoveisSlugRoute = ImoveisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImoveisRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/imoveis': typeof ImoveisIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/imoveis': typeof ImoveisRouteWithChildren
  '/projetos': typeof ProjetosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/imoveis/$slug': typeof ImoveisSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/imoveis/': typeof ImoveisIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contato'
    | '/imoveis'
    | '/projetos'
    | '/sobre'
    | '/blog/$slug'
    | '/imoveis/$slug'
    | '/projetos/$slug'
    | '/blog/'
    | '/imoveis/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/sobre'
    | '/blog/$slug'
    | '/imoveis/$slug'
    | '/projetos/$slug'
    | '/blog'
    | '/imoveis'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contato'
    | '/imoveis'
    | '/projetos'
    | '/sobre'
    | '/blog/$slug'
    | '/imoveis/$slug'
    | '/projetos/$slug'
    | '/blog/'
    | '/imoveis/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  ImoveisRoute: typeof ImoveisRouteWithChildren
  ProjetosRoute: typeof ProjetosRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/imoveis/': {
      id: '/imoveis/'
      path: '/'
      fullPath: '/imoveis/'
      preLoaderRoute: typeof ImoveisIndexRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/imoveis/$slug': {
      id: '/imoveis/$slug'
      path: '/$slug'
      fullPath: '/imoveis/$slug'
      preLoaderRoute: typeof ImoveisSlugRouteImport
      parentRoute: typeof ImoveisRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ImoveisRouteChildren {
  ImoveisSlugRoute: typeof ImoveisSlugRoute
  ImoveisIndexRoute: typeof ImoveisIndexRoute
}

const ImoveisRouteChildren: ImoveisRouteChildren = {
  ImoveisSlugRoute: ImoveisSlugRoute,
  ImoveisIndexRoute: ImoveisIndexRoute,
}

const ImoveisRouteWithChildren =
  ImoveisRoute._addFileChildren(ImoveisRouteChildren)

interface ProjetosRouteChildren {
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosSlugRoute: ProjetosSlugRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  ImoveisRoute: ImoveisRouteWithChildren,
  ProjetosRoute: ProjetosRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
